name: Weekly Security Scan

on:
  schedule:
    - cron: '0 6 * * 1' # Mondays at 06:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout Liferay portal repo
        uses: actions/checkout@v3
        with:
          repository: liferay/liferay-portal
          token: ${{ secrets.LIFERAY_PAT }}
          path: liferay-portal

      - name: Checkout sca-packages repo
        uses: actions/checkout@v3
        with:
          repository: lr-whitehat/liferay-sca-packages
          token: ${{ secrets.LIFERAY_PAT }}
          path: liferay-sca-packages

      - name: Ant setup
        run: |
          sudo apt-get update
          sudo apt-get install -y ant

      - name: Run vulnerability scanner
        run: |
          ant compile
          ant run

      - name: Show HTML file last modified date
        run: |
          echo "Last modified:"
          stat -c '%y'  ${GITHUB_WORKSPACE}/liferay-sca-packages/master/sonatype-oss-index-report.html
          echo "Current system date:"
          date +"%Y-%m-%d %H:%M:%S"

      - name: Upload report as GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: liferay-sca-packages/master/

  deploy:
    needs: security-scan
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
